<?php
/**
 * Media Library integration — upload conversion, original cleanup, and metadata replacement.
 *
 * @package Webp_Avif_Images_Converter
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Webp_Avif_Images_Converter_Media
 *
 * Hooks into the WordPress upload pipeline to convert uploaded PNG/JPEG/GIF images
 * to WebP and/or AVIF using GD. Deletes originals and rewrites attachment metadata
 * so WordPress treats the converted files as the canonical images.
 */
class Webp_Avif_Images_Converter_Media {

	/**
	 * Option name for plugin settings.
	 *
	 * @var string
	 */
	private const OPTION_NAME = 'webp_avif_images_converter_settings';

	/**
	 * Metadata key used to store conversion data in _wp_attachment_metadata.
	 *
	 * @var string
	 */
	private const META_KEY = 'webp_avif_converter';

	/**
	 * MIME type mapping from input format to output format.
	 *
	 * @var array<string, array<string, string>>
	 */
	private const MIME_MAP = array(
		'webp' => 'image/webp',
		'avif' => 'image/avif',
	);

	/**
	 * Constructor — register WordPress hooks.
	 */
	public function __construct() {
		add_filter( 'wp_generate_attachment_metadata', array( $this, 'handle_upload' ), 99, 2 );
		add_action( 'delete_attachment', array( $this, 'delete_attachment' ), 10, 1 );
		add_action( 'admin_notices', array( $this, 'avif_failed_notice' ) );
	}

	/**
	 * Convert uploaded image, delete originals, and rewrite metadata.
	 *
	 * Hooks into wp_generate_attachment_metadata at priority 99.
	 *
	 * @param array $metadata      Attachment metadata generated by WordPress.
	 * @param int   $attachment_id The attachment post ID.
	 *
	 * @return array Rewritten metadata pointing to converted files.
	 */
	public function handle_upload( array $metadata, int $attachment_id ): array {
		$mime = get_post_mime_type( $attachment_id );
		if ( ! $mime || 0 !== strpos( $mime, 'image/' ) ) {
			return $metadata;
		}

		$allowed_mimes = array( 'image/png', 'image/jpeg', 'image/jpg', 'image/gif' );
		if ( ! in_array( $mime, $allowed_mimes, true ) ) {
			return $metadata;
		}

		$settings = get_option( self::OPTION_NAME, array() );
		if ( ! is_array( $settings ) || empty( $settings['output_formats'] ) ) {
			return $metadata;
		}

		$mime_map     = array(
			'image/png'  => 'png',
			'image/jpeg' => 'jpg',
			'image/jpg'  => 'jpg',
			'image/gif'  => 'gif',
		);
		$input_format = $mime_map[ $mime ] ?? '';
		$input_formats = $settings['input_formats'] ?? array( 'png', 'jpg', 'gif' );
		if ( ! in_array( $input_format, $input_formats, true ) ) {
			return $metadata;
		}

		$upload_dir = wp_upload_dir();
		$basedir    = $upload_dir['basedir'];

		$file       = $metadata['file'] ?? '';
		$source_dir = $basedir . '/' . pathinfo( $file, PATHINFO_DIRNAME );
		$filename   = pathinfo( $file, PATHINFO_FILENAME );

		$converted_files = array(
			'original' => array( 'webp' => null, 'avif' => null ),
			'sizes'    => array(),
		);

		// Convert original image.
		$result = Webp_Avif_Images_Converter_Converter::convert(
			$basedir . '/' . $file,
			$source_dir,
			$filename,
			$settings
		);

		$primary_format = null;
		if ( ! is_wp_error( $result ) ) {
			$converted_files['original'] = $this->to_relative_paths( $result, $basedir );
			$primary_format = $this->pick_primary_format( $converted_files['original'] );
		}

		// Convert each sub-size.
		$sizes = $metadata['sizes'] ?? array();
		foreach ( $sizes as $size_name => $size_data ) {
			$size_file = $size_data['file'] ?? '';
			if ( empty( $size_file ) ) {
				continue;
			}

			$size_dir         = $basedir . '/' . pathinfo( $file, PATHINFO_DIRNAME );
			$size_name_no_ext = pathinfo( $size_file, PATHINFO_FILENAME );

			$result = Webp_Avif_Images_Converter_Converter::convert(
				$size_dir . '/' . $size_file,
				$size_dir,
				$size_name_no_ext,
				$settings
			);

			if ( ! is_wp_error( $result ) ) {
				$converted_files['sizes'][ $size_name ] = $this->to_relative_paths( $result, $basedir );
			}
		}

		// If no primary format was determined, bail out — keep originals.
		if ( null === $primary_format ) {
			return $metadata;
		}

		// Delete original files from disk.
		$original_full = $basedir . '/' . $file;
		if ( file_exists( $original_full ) ) {
			wp_delete_file( $original_full );
		}
		foreach ( $sizes as $size_data ) {
			$size_file = $size_data['file'] ?? '';
			if ( empty( $size_file ) ) {
				continue;
			}
			$size_full = $basedir . '/' . pathinfo( $file, PATHINFO_DIRNAME ) . '/' . $size_file;
			if ( file_exists( $size_full ) ) {
				wp_delete_file( $size_full );
			}
		}

		// Rewrite metadata to point to converted files.
		$dir = pathinfo( $file, PATHINFO_DIRNAME );
		$dir = '.' === $dir ? '' : $dir . '/';

		$metadata['file'] = $dir . $filename . '.' . $primary_format;

		// Update MIME type and attached file.
		$new_mime = self::MIME_MAP[ $primary_format ] ?? 'image/webp';
		wp_update_post(
			array(
				'ID'             => $attachment_id,
				'post_mime_type' => $new_mime,
			)
		);
		update_attached_file( $attachment_id, $metadata['file'] );

		// Rewrite sub-size file references.
		foreach ( $sizes as $size_name => &$size_data ) {
			$size_file = $size_data['file'] ?? '';
			if ( empty( $size_file ) ) {
				continue;
			}
			$size_data['file'] = pathinfo( $size_file, PATHINFO_FILENAME ) . '.' . $primary_format;
			$size_data['mime-type'] = $new_mime;
		}
		unset( $size_data );
		$metadata['sizes'] = $sizes;

		// Inject conversion metadata for housekeeping.
		$metadata[ self::META_KEY ] = array(
			'version'       => WPAC_VERSION,
			'converted_at'  => time(),
			'primary_format' => $primary_format,
			'files'          => $converted_files,
		);

		// Detect AVIF requested but not generated — show admin notice.
		if ( in_array( 'avif', $settings['output_formats'] ?? array(), true ) ) {
			$avif_generated = ! empty( $converted_files['original']['avif'] );
			if ( ! $avif_generated ) {
				set_transient( 'wpac_avif_failed_notice', true, 300 );
			}
		}

		return $metadata;
	}

	/**
	 * Delete converted files when an attachment is permanently deleted.
	 *
	 * @param int $attachment_id The attachment post ID.
	 */
	public function delete_attachment( int $attachment_id ): void {
		$metadata = wp_get_attachment_metadata( $attachment_id );
		if ( ! is_array( $metadata ) || empty( $metadata[ self::META_KEY ] ) ) {
			return;
		}

		$converted  = $metadata[ self::META_KEY ];
		$upload_dir = wp_upload_dir();
		$basedir    = $upload_dir['basedir'];

		$files_to_delete = array();

		if ( ! empty( $converted['files']['original'] ) ) {
			foreach ( $converted['files']['original'] as $path ) {
				if ( $path ) {
					$files_to_delete[] = $basedir . '/' . $path;
				}
			}
		}

		if ( ! empty( $converted['files']['sizes'] ) ) {
			foreach ( $converted['files']['sizes'] as $size_files ) {
				foreach ( $size_files as $path ) {
					if ( $path ) {
						$files_to_delete[] = $basedir . '/' . $path;
					}
				}
			}
		}

		foreach ( $files_to_delete as $absolute_path ) {
			if ( file_exists( $absolute_path ) ) {
				wp_delete_file( $absolute_path );
			}
		}
	}

	/**
	 * Pick the primary output format — WebP preferred over AVIF.
	 *
	 * @param array $converted ['webp' => string|null, 'avif' => string|null].
	 *
	 * @return string|null 'webp', 'avif', or null if nothing was converted.
	 */
	private function pick_primary_format( array $converted ): ?string {
		if ( ! empty( $converted['webp'] ) ) {
			return 'webp';
		}
		if ( ! empty( $converted['avif'] ) ) {
			return 'avif';
		}
		return null;
	}

	/**
	 * Convert absolute file paths to paths relative to the uploads base directory.
	 *
	 * @param array  $result  Conversion result ['webp' => string|null, 'avif' => string|null].
	 * @param string $basedir Absolute path to the uploads base directory.
	 *
	 * @return array Relative paths ['webp' => string|null, 'avif' => string|null].
	 */
	private function to_relative_paths( array $result, string $basedir ): array {
		$relative = array();

		foreach ( array( 'webp', 'avif' ) as $format ) {
			if ( ! empty( $result[ $format ] ) ) {
				$relative[ $format ] = ltrim( str_replace( $basedir . '/', '', $result[ $format ] ), '/' );
			} else {
				$relative[ $format ] = null;
			}
		}

		return $relative;
	}

	/**
	 * Show admin notice when AVIF was requested but conversion failed.
	 */
	public function avif_failed_notice(): void {
		if ( ! get_transient( 'wpac_avif_failed_notice' ) ) {
			return;
		}

		delete_transient( 'wpac_avif_failed_notice' );

		$avif_available = function_exists( 'imageavif' ) && ( imagetypes() & IMG_AVIF );
		if ( $avif_available ) {
			$message = __( 'WebP & AVIF Converter: la conversión a AVIF falló. El archivo pudo estar corrupto o ser demasiado grande. Solo se generó WebP.', 'webp-avif-images-converter' );
		} else {
			$message = __( 'WebP & AVIF Converter: AVIF no está disponible en este servidor porque GD no tiene soporte para imageavif(). Solo se generó WebP. Desactivá AVIF en los ajustes para eliminar este aviso.', 'webp-avif-images-converter' );
		}

		printf(
			'<div class="notice notice-warning is-dismissible"><p>%s</p></div>',
			esc_html( $message )
		);
	}
}
