<?php
/**
 * Media Library integration — upload conversion and file cleanup.
 *
 * @package Webp_Avif_Images_Converter
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Webp_Avif_Images_Converter_Media
 *
 * Hooks into the WordPress upload pipeline to convert uploaded PNG/JPEG images
 * to WebP and/or AVIF using GD. Augments attachment metadata with references to
 * converted files and cleans them up on attachment deletion.
 */
class Webp_Avif_Images_Converter_Media {

	/**
	 * Option name for plugin settings.
	 *
	 * @var string
	 */
	private const OPTION_NAME = 'webp_avif_images_converter_settings';

	/**
	 * Metadata key used to store conversion data in _wp_attachment_metadata.
	 *
	 * @var string
	 */
	private const META_KEY = 'webp_avif_converter';

	/**
	 * Constructor — register WordPress hooks.
	 */
	public function __construct() {
		add_filter( 'wp_generate_attachment_metadata', array( $this, 'handle_upload' ), 99, 2 );
		add_action( 'delete_attachment', array( $this, 'delete_attachment' ), 10, 1 );
	}

	/**
	 * Convert uploaded image and all sub-sizes to WebP/AVIF.
	 *
	 * Hooks into wp_generate_attachment_metadata at priority 99.
	 * Receives metadata AFTER WordPress has processed all sub-sizes.
	 *
	 * @param array   $metadata      Attachment metadata generated by WordPress.
	 * @param int     $attachment_id The attachment post ID.
	 *
	 * @return array Modified metadata with webp_avif_converter key.
	 */
	public function handle_upload( array $metadata, int $attachment_id ): array {
		// Skip non-image attachments.
		$mime = get_post_mime_type( $attachment_id );
		if ( ! $mime || 0 !== strpos( $mime, 'image/' ) ) {
			return $metadata;
		}

		// Only convert PNG and JPEG.
		$allowed_mimes = array( 'image/png', 'image/jpeg', 'image/jpg' );
		if ( ! in_array( $mime, $allowed_mimes, true ) ) {
			return $metadata;
		}

		// Load settings.
		$settings = get_option( self::OPTION_NAME, array() );
		if ( ! is_array( $settings ) || empty( $settings['output_formats'] ) ) {
			return $metadata;
		}

		// Check input format against settings.
		$input_format = ( 'image/png' === $mime ) ? 'png' : 'jpg';
		$input_formats = $settings['input_formats'] ?? array( 'png', 'jpg' );
		if ( ! in_array( $input_format, $input_formats, true ) ) {
			return $metadata;
		}

		// Get upload directory info.
		$upload_dir = wp_upload_dir();
		$basedir    = $upload_dir['basedir'];

		// Build the path to the original file.
		$file       = $metadata['file'] ?? '';
		$source_dir = $basedir . '/' . pathinfo( $file, PATHINFO_DIRNAME );
		$filename   = pathinfo( $file, PATHINFO_FILENAME );

		$converted_files = array(
			'original' => array(
				'webp' => null,
				'avif' => null,
			),
			'sizes'    => array(),
		);

		// Convert original image.
		$result = Webp_Avif_Images_Converter_Converter::convert(
			$basedir . '/' . $file,
			$source_dir,
			$filename,
			$settings
		);

		if ( ! is_wp_error( $result ) ) {
			$converted_files['original'] = $this->to_relative_paths( $result, $basedir );
		}

		// Convert each sub-size.
		$sizes = $metadata['sizes'] ?? array();
		foreach ( $sizes as $size_name => $size_data ) {
			$size_file = $size_data['file'] ?? '';
			if ( empty( $size_file ) ) {
				continue;
			}

			$size_dir  = $basedir . '/' . pathinfo( $file, PATHINFO_DIRNAME );
			$size_name_no_ext = pathinfo( $size_file, PATHINFO_FILENAME );

			$result = Webp_Avif_Images_Converter_Converter::convert(
				$size_dir . '/' . $size_file,
				$size_dir,
				$size_name_no_ext,
				$settings
			);

			if ( ! is_wp_error( $result ) ) {
				$converted_files['sizes'][ $size_name ] = $this->to_relative_paths( $result, $basedir );
			}
		}

		// Inject conversion metadata.
		$metadata[ self::META_KEY ] = array(
			'version'      => WPAC_VERSION,
			'converted_at' => time(),
			'files'        => $converted_files,
		);

		return $metadata;
	}

	/**
	 * Delete converted files when an attachment is permanently deleted.
	 *
	 * @param int $attachment_id The attachment post ID.
	 */
	public function delete_attachment( int $attachment_id ): void {
		$metadata = wp_get_attachment_metadata( $attachment_id );
		if ( ! is_array( $metadata ) || empty( $metadata[ self::META_KEY ] ) ) {
			return;
		}

		$converted = $metadata[ self::META_KEY ];
		$upload_dir = wp_upload_dir();
		$basedir    = $upload_dir['basedir'];

		$files_to_delete = array();

		// Collect original converted files.
		if ( ! empty( $converted['files']['original'] ) ) {
			foreach ( $converted['files']['original'] as $path ) {
				if ( $path ) {
					$files_to_delete[] = $basedir . '/' . $path;
				}
			}
		}

		// Collect sub-size converted files.
		if ( ! empty( $converted['files']['sizes'] ) ) {
			foreach ( $converted['files']['sizes'] as $size_files ) {
				foreach ( $size_files as $path ) {
					if ( $path ) {
						$files_to_delete[] = $basedir . '/' . $path;
					}
				}
			}
		}

		// Delete each file, silently skip if already missing.
		foreach ( $files_to_delete as $absolute_path ) {
			if ( file_exists( $absolute_path ) ) {
				wp_delete_file( $absolute_path );
			}
		}
	}

	/**
	 * Convert absolute file paths to paths relative to the uploads base directory.
	 *
	 * @param array  $result  Conversion result ['webp' => string|null, 'avif' => string|null].
	 * @param string $basedir Absolute path to the uploads base directory.
	 *
	 * @return array Relative paths ['webp' => string|null, 'avif' => string|null].
	 */
	private function to_relative_paths( array $result, string $basedir ): array {
		$relative = array();

		foreach ( array( 'webp', 'avif' ) as $format ) {
			if ( ! empty( $result[ $format ] ) ) {
				// Strip the basedir prefix and leading slash.
				$relative[ $format ] = ltrim( str_replace( $basedir . '/', '', $result[ $format ] ), '/' );
			} else {
				$relative[ $format ] = null;
			}
		}

		return $relative;
	}
}
